export const countryOptions = [
  { iso3: "USA", iso2: "US", lang: "EN" },
  { iso3: "GBR", iso2: "GB", lang: "EN" },
  { iso3: "FRA", iso2: "FR", lang: "FR" },
  { iso3: "POL", iso2: "PL", lang: "EN" },
  { iso3: "SVK", iso2: "SK", lang: "EN" },
  { iso3: "DEU", iso2: "DE", lang: "DE" },
  { iso3: "ESP", iso2: "ES", lang: "ES" },
  { iso3: "PRT", iso2: "PT", lang: "PT" },
  { iso3: "GRC", iso2: "GR", lang: "EN" },
  { iso3: "NLD", iso2: "NL", lang: "NL" },
  { iso3: "SWE", iso2: "SE", lang: "EN" },
  { iso3: "NOR", iso2: "NO", lang: "NO" },
  { iso3: "DNK", iso2: "DK", lang: "EN" },
  { iso3: "KOR", iso2: "KR", lang: "EN" },
  { iso3: "JPN", iso2: "JP", lang: "EN" },
  { iso3: "CHN", iso2: "CN", lang: "EN" },
  { iso3: "ITA", iso2: "IT", lang: "IT" },
  { iso3: "TUR", iso2: "TR", lang: "EN" },
  { iso3: "MEX", iso2: "MX", lang: "EN" },
  { iso3: "THA", iso2: "TH", lang: "EN" },
  { iso3: "EGY", iso2: "EG", lang: "EN" },
  { iso3: "CAN", iso2: "CA", lang: "EN" },
  { iso3: "CUB", iso2: "CU", lang: "EN" },
  { iso3: "RUS", iso2: "RU", lang: "RU" },
];
