export const countryOptions = [
  { iso3: "FRA", iso2: "FR" },
  { iso3: "USA", iso2: "US" },
  { iso3: "GBR", iso2: "GB" },
  { iso3: "POL", iso2: "PL" },
  { iso3: "SVK", iso2: "SK" },
  { iso3: "DEU", iso2: "DE" },
  { iso3: "ESP", iso2: "ES" },
  { iso3: "PRT", iso2: "PT" },
  { iso3: "GRC", iso2: "GR" },
  { iso3: "NLD", iso2: "NL" },
  { iso3: "SWE", iso2: "SE" },
  { iso3: "NOR", iso2: "NO" },
  { iso3: "DNK", iso2: "DK" },
  { iso3: "KOR", iso2: "KR" },
  { iso3: "JPN", iso2: "JP" },
  { iso3: "CHN", iso2: "CN" },
  { iso3: "ITA", iso2: "IT" },
  { iso3: "TUR", iso2: "TR" },
  { iso3: "MEX", iso2: "MX" },
  { iso3: "THA", iso2: "TH" },
  { iso3: "EGY", iso2: "EG" },
  { iso3: "CAN", iso2: "CA" },
  { iso3: "CUB", iso2: "CU" },
  { iso3: "RUS", iso2: "RU" },
];
